defmodule ColouredFlowDashboardWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :coloured_flow_dashboard

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_coloured_flow_dashboard_key",
    signing_salt: "j9F78qE3",
    same_site: "Lax"
  ]

  # The dashboard has no authentication and no per-user session state, so the
  # Musubi socket does not need `connect_info: [session: ...]`. Mounting with
  # `session:` is also actively broken against Musubi 0.6: Phoenix's session
  # fetcher emits `connect_info[:session] = nil` when the client has no cookie
  # yet (e.g. first visit), and `Musubi.Transport.Socket.build_connect_socket/2`
  # then forwards that nil to `Musubi.Socket.put_session/2` which only matches
  # `is_map(session)` and crashes the WS handshake with HTTP 500. Mirrors the
  # reference apps under arbor/examples/{cart_page,chat_room,poll_app}.
  socket "/socket", ColouredFlowDashboardWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :coloured_flow_dashboard,
    gzip: not code_reloading?,
    only: ColouredFlowDashboardWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :coloured_flow_dashboard
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ColouredFlowDashboardWeb.Router
end
